security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login: 
            pattern: ^/login
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - App\Security\BasicAuthenticator

        main:
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - App\Security\JWTAuthenticator

    access_control:
        - { path: ^/profile, roles: ROLE_USER }
